Repository web-mighty-io/web-mighty, pull requests merged in 2020-10, with the labels that each got.

#13 Made basic structure of game
  core/src/base.rs
  core/src/basic.rs
  util/start_server.py
Labels: 1-core, 2-enhancement, 3-rust

#15 moving to github actions (#14)
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  Cargo.toml
Labels: 1-other, 2-enhancement, 3-other

#16 Moving to github actions (#14)
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .travis.yml
Labels: 1-other, 2-enhancement, 3-other

#18 Added more tests
  core/src/base.rs
  core/src/basic.rs
  core/src/user.rs
  public/Cargo.toml
Labels: 1-core, 2-enhancement, 3-rust

#20 Added clippy in ci
  .github/workflows/build.yml
  core/src/base.rs
  core/src/basic.rs
Labels: 1-other, 2-enhancement, 3-other

#21 :construction_worker: added names to each step
  .github/workflows/build.yml
Labels: 1-other, 2-enhancement, 3-other

#22 ✨ made in-game behavior
  core/src/base.rs
  core/src/basic.rs
Labels: 1-core, 2-enhancement, 3-rust

#28 🎨 added bulma
  .gitignore
  public/static/assets/spade_A.png
  public/static/css/style.css
  public/static/index.html
  public/static/sass/mystyles.scss
  util/start_server.py
Labels: 1-client-web, 1-util, 2-enhancement, 3-python, 3-rust

#29 🎨 changed structure & added errors
  mighty/src/base.rs
  mighty/src/basic.rs
  mighty/src/error.rs
  mighty/src/lib.rs
  mighty/src/user.rs
  public/static/css/style.css.map
Labels: 1-core, 2-enhancement, 3-rust

#30 🎨 changed friend & command to basic
  mighty/src/base.rs
  mighty/src/basic.rs
Labels: 1-core, 2-enhancement, 3-rust

#33 Web structure
  public/static/main.html
Labels: 1-client-web, 2-enhancement, 3-html/css, 3-javascript

#35 :construction_worker: changed to actions-rs
  .github/workflows/coverage.yml
Labels: 1-util, 2-enhancement, 3-other

#36 👷 added features
  .github/workflows/build.yml
Labels: 1-util, 2-enhancement, 3-other

#34 ✨ make file watching server (for feature)
  .gitignore
  public/static/css/style.css.map
  public/static/index.hbs
  public/static/main.hbs
  public/static/res/.ignore
  public/static/res/assets/spade_A.png
  public/static/res/js/mighy.js
  public/static/res/scss/style.scss
  server/Cargo.toml
  server/src/app_state.rs
  server/src/lib.rs
  server/src/main.rs
  server/src/util.rs
  util/start_server.py
Labels: 1-server-http, 2-enhancement, 3-rust

#38 👷 fixed ci
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  server/src/app_state.rs
Labels: 1-other, 2-enhancement, 3-other

#39 ✨ enabled https
  .gitignore
  server/Cargo.toml
  server/src/app_state.rs
  server/src/https.rs
  server/src/lib.rs
  server/src/main.rs
  server/src/util.rs
  util/gen_self_cert.sh
Labels: 1-server-http, 2-enhancement, 3-rust

#40 :fire: removed cert gen file
  server/src/app_state.rs
  server/src/main.rs
  util/gen_self_cert.sh
Labels: 1-server-http, 1-util, 2-enhancement, 3-other, 3-rust

#43 📝 added instruction & badges
  README.md
Labels: 1-other, 2-documentation, 3-other
