Repository web-mighty-io/web-mighty, pull requests merged in 2020-11, with the labels that each got.

#44 :building_construction: improving profile.html
  public/static/profile.html
Labels: 1-client-web, 2-enhancement, 3-html/css, hacktoberfest-accepted

#45 🐛 fixed for windows
  server/src/app_state.rs
Labels: 1-server-http, 2-enhancement, 3-rust

#47 ✨ added postgresql support
  .gitignore
  server/Cargo.toml
  server/src/db/login.rs
  server/src/db/mod.rs
  server/src/db/register.rs
  server/src/handlers/get.rs
  server/src/handlers/mod.rs
  server/src/handlers/post.rs
  server/src/lib.rs
  server/src/main.rs
Labels: 1-server-http, 2-enhancement, 3-rust

#51 :art: changed structure
  mighty/src/base.rs
  mighty/src/basic.rs
  mighty/src/lib.rs
  mighty/src/user.rs
Labels: 1-core, 2-enhancement, 3-rust

#54 :sparkles: made generate function
  mighty/src/base.rs
  mighty/src/basic.rs
Labels: 1-core, 2-enhancement, 3-rust

#55 :art: changed game
  mighty/src/base.rs
  mighty/src/basic.rs
Labels: 1-core, 2-enhancement, 3-rust

#57 :construction_worker: fixed to all targets
  .github/workflows/build.yml
Labels: 1-other, 2-enhancement, 3-other

#59 :see_no_evil: added Cargo.lock
  .gitignore
  Cargo.lock
Labels: 1-other, 2-enhancement, 3-other

#60 :construction_worker: added cargo-audit
  .github/workflows/audit.yml
Labels: 1-other, 2-enhancement, 3-other

#66 ✨ starting websocket
  .github/workflows/audit.yml
  .gitignore
  Cargo.lock
  server/Cargo.toml
  server/src/app_state.rs
  server/src/game/mod.rs
  server/src/game/server.rs
  server/src/game/session.rs
  server/src/handlers/get.rs
  server/src/handlers/mod.rs
  server/src/lib.rs
  server/src/main.rs
Labels: 1-server-websocket, 2-enhancement, 3-rust

#67 :sparkles: using serde
  .gitignore
  Cargo.lock
  mighty/Cargo.toml
  mighty/src/base.rs
  mighty/src/basic.rs
  mighty/src/error.rs
  rustfmt.toml
  server/src/app_state.rs
  server/src/db/login.rs
  server/src/db/register.rs
  server/src/handlers/get.rs
  server/src/handlers/post.rs
  server/src/https.rs
  server/src/main.rs
Labels: 1-core, 2-enhancement, 3-rust

#69 :white_check_mark: changed tests
  mighty/src/base.rs
  mighty/src/basic.rs
Labels: 1-core, 2-test, 3-rust

#70 :art: added room
  mighty/Cargo.toml
  mighty/src/base.rs
  mighty/src/basic.rs
  mighty/src/error.rs
  server/Cargo.toml
  server/src/app_state.rs
  server/src/game/mod.rs
  server/src/game/room.rs
  server/src/game/server.rs
  server/src/game/session.rs
  server/src/main.rs
Labels: 1-server-websocket, 2-enhancement, 3-rust

#71 :green_heart: upgraded toolchain
  .github/workflows/coverage.yml
Labels: 1-other, 2-enhancement, 3-other
