Repository web-mighty-io/web-mighty, pull requests merged in 2021-01, with the labels that each got.

#90 :hammer: added minifying feature to dockerfile
  Dockerfile
  README.md
  minify_files.py
  requirements.txt
  server.docker.toml
  start_server.py
  static/res/.ignore
Labels: 1-util, 2-enhancement, 3-other

#92 :hammer: changed minifying process
  Dockerfile
  minify_files.py
Labels: 1-util, 2-enhancement, 3-other, 3-python

#99 :wrench: added .kodiak.toml
  .kodiak.toml
  LICENSE
Labels: automerge

#100 :boom: reconstructed structure
  server/Cargo.toml
  server/src/actor/db/game.rs
  server/src/actor/db/mod.rs
  server/src/actor/db/user.rs
  server/src/actor/group.rs
  server/src/actor/hub.rs
  server/src/actor/list.rs
  server/src/actor/main.rs
  server/src/actor/mod.rs
  server/src/actor/room.rs
  server/src/actor/user.rs
  server/src/app_state.rs
  server/src/config.rs
  server/src/db/game.rs
  server/src/db/mod.rs
  server/src/db/user.rs
  server/src/https.rs
  server/src/lib.rs
  server/src/service/delete.rs
  server/src/service/get/mod.rs
  server/src/service/get/ws.rs
  server/src/service/mod.rs
  server/src/service/post.rs
  server/src/util.rs
  types/src/lib.rs
Labels: 1-server-websocket, 2-enhancement, 3-rust, automerge

#101 :wrench: changed configuration of server
  Dockerfile
  README.md
  server/Cargo.toml
  server/src/config.rs
  server/src/lib.rs
Labels: 1-server-http, 2-enhancement, 3-other, 3-rust, automerge

#95 card.rs testing
  mighty/src/card.rs
Labels: automerge

#103 :art: implemented basic functions
  public/Cargo.toml
  public/src/global.rs
  public/src/lib.rs
  public/src/rule.rs
  public/src/ws/room_user.rs
Labels: 1-client-wasm, 2-enhancement, 3-rust, automerge

#104 :art: changed rule
  public/Cargo.toml
  public/src/global.rs
  public/src/lib.rs
  public/src/rule.rs
  public/src/ws/room_user.rs
Labels: 1-client-wasm, 2-enhancement, 3-rust, automerge

#102 added client feature
  mighty/src/state.rs
Labels: 1-mighty, 2-enhancement, 3-rust, automerge

#107 :construction_worker: added ci
  .github/workflows/build.yml
  .github/workflows/clippy.yml
  .github/workflows/coverage.yml
  .github/workflows/fmt.yml
  .github/workflows/test.yml
Labels: 1-other, 2-enhancement, 3-other, automerge

#108 room page
  static/404.hbs
  static/game.hbs
  static/index.hbs
  static/main.hbs
  static/main.html
  static/profile.html
  static/res/assets/account_circle-24px.svg
  static/res/assets/settings-24px.svg
  static/res/scss/style.scss
  static/rooms.hbs
  static/settings.hbs
Labels: 1-client-web, 2-enhancement, 3-html/css, automerge

#110 :art: changed configuration default values
  .kodiak.toml
  server/src/config.rs
Labels: 1-other, 2-enhancement, 3-other, automerge

#112 :art: improved sql
  .github/workflows/deploy.yml
  Dockerfile
  server/src/db/game.rs
  server/src/lib.rs
  sql/create_room.sql
  sql/create_user.sql
Labels: 1-other, 2-enhancement, 3-other, automerge

#113 :green_heart: changed deploy.yml
  .github/workflows/deploy.yml
Labels: 1-other, 2-enhancement, 3-other, automerge

#114 added state test
  mighty/src/error.rs
  mighty/src/rule/mod.rs
  mighty/src/rule/timing.rs
  mighty/src/state.rs
  server/src/db/user.rs
Labels: 1-mighty, 2-enhancement, 3-rust, automerge

#115 :memo: wrote documentation
  README.md
  mighty/src/command.rs
  mighty/src/game.rs
  mighty/src/rule/mod.rs
  mighty/src/state.rs
  minify_files.py
  server/src/actor/hub.rs
  server/src/actor/list.rs
  server/src/actor/main.rs
  server/src/actor/observe.rs
  server/src/actor/room.rs
  server/src/actor/room_user.rs
  server/src/actor/session.rs
  server/src/actor/user.rs
  server/src/app_state.rs
  server/src/config.rs
  server/src/db/game.rs
  server/src/error.rs
  server/src/https.rs
  server/src/lib.rs
  server/src/main.rs
  server/src/util.rs
  types/Cargo.toml
  types/src/lib.rs
Labels: 1-server-http, 1-server-websocket, 2-documentation, 2-enhancement, 3-rust, automerge

#116 :art: changed session for callback support
  public/src/ws/list.rs
  public/src/ws/main.rs
  public/src/ws/observe.rs
  public/src/ws/room_user.rs
  public/src/ws/session.rs
Labels: 1-client-wasm, 2-enhancement, 3-rust, automerge

#117 :bug: fixed simple bug
  public/src/ws/session.rs
Labels: 1-client-wasm, 2-bug, 3-rust, automerge

#118 :art: implemented public
  public/src/lib.rs
  public/src/rule.rs
  public/src/ws/list.rs
  public/src/ws/main.rs
  public/src/ws/observe.rs
  public/src/ws/room_user.rs
  public/src/ws/session.rs
Labels: 1-client-wasm, 2-enhancement, 3-rust, automerge

#121 :sparkles: added mail feature
  server/Cargo.toml
  server/src/actor/mail.rs
  server/src/config.rs
  server/src/db/user.rs
  server/src/service/mod.rs
  server/src/service/post.rs
  types/src/lib.rs
Labels: 1-client-wasm, 1-client-web, 2-enhancement, 3-rust, automerge

#122 Fixed Codacy
  Dockerfile
  README.md
  minify_files.py
  server/README.md
  static/res/js/index.js
  static/res/js/mighy.js
  static/res/scss/style.scss
Labels: 1-other, 2-documentation, 3-other, automerge

#123 :wrench: fixed dockerfile
  .github/workflows/coverage.yml
  .github/workflows/docker.yml
  Dockerfile
Labels: 1-other, 2-enhancement, 3-other, automerge

#124 :rotating_light: fixed codacy issue
  minify_files.py
Labels: 1-other, 2-documentation, 3-python, automerge

#125 :art: fixed configuration
  server.docker.toml
  server.sample.toml
  server/src/config.rs
  server/src/lib.rs
Labels: 1-server-http, 2-enhancement, 3-rust, automerge

#126 :memo: edited badges
  .github/workflows/docker.yml
  README.md
Labels: 1-other, 2-documentation, 3-other, automerge

#127 :wrench: changed wasm to release
  Dockerfile
  README.md
  server.sample.toml
Labels: 1-other, 2-documentation, 3-other, automerge

#128 :memo: changed for docker
  README.md
  server/README.md
  server/src/config.rs
  server/src/lib.rs
Labels: 1-server-http, 2-bug, 3-rust, automerge

#129 :memo: updated README.md
  README.md
Labels: 1-other, 2-documentation, 3-other, automerge

#131 💥 removed uuid
  mighty/Cargo.toml
  mighty/src/card.rs
  mighty/src/lib.rs
  mighty/src/state.rs
  public/Cargo.toml
  public/src/global.rs
  public/src/lib.rs
  public/src/ws/list.rs
  public/src/ws/main.rs
  public/src/ws/observe.rs
  public/src/ws/room_user.rs
  public/src/ws/session.rs
  server/Cargo.toml
  server/src/actor/hub.rs
  server/src/actor/mail.rs
  server/src/actor/room.rs
  server/src/db/game.rs
  server/src/db/user.rs
  server/src/service/post.rs
  static/res/js/mighy.js
  static/res/js/user.js
  static/res/js/ws.js
  static/res/scss/style.scss
  types/Cargo.toml
  types/src/lib.rs
Labels: 1-server-http, 2-enhancement, 3-rust, automerge

#132 :memo: updated badge
  README.md
Labels: 2-documentation, automerge
