Repository web-mighty-io/web-mighty, pull requests merged in 2021-02, with the labels that each got.

#133 :bento: added npm for better dependency control
  .codecov.yml
  .github/workflows/build.yml
  .github/workflows/clippy.yml
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  .gitignore
  Cargo.toml
  Dockerfile
  client/Cargo.toml
  client/src/lib.rs
  client/src/ws/list.rs
  client/src/ws/main.rs
  client/src/ws/mod.rs
  client/src/ws/observe.rs
  client/src/ws/room_user.rs
  client/src/ws/session.rs
  client/tests/web.rs
  minify_files.py
  package.json
  public/404.hbs
  public/game.hbs
  public/index.hbs
  public/main.hbs
  public/res/assets/404.png
  public/res/assets/404.svg
  public/res/assets/account_circle-24px.svg
  public/res/assets/settings-24px.svg
  public/res/assets/spade_A.png
  public/res/js/index.js
  public/res/js/modules/user.js
  public/res/js/modules/ws.js
  public/res/scss/style.scss
  public/rooms.hbs
  public/settings.hbs
  server.sample.toml
  server/src/app_state.rs
  server/src/config.rs
  static/res/js/ws.js
Labels: 2-enhancement, automerge

#135 Added webpack support
  .gitignore
  Dockerfile
  README.md
  client/src/ws/session.rs
  package.json
  public/js/index.js
  public/js/modules/user.js
  public/js/modules/ws.js
  public/res/js/index.js
  public/res/js/modules/ws.js
  server/Cargo.toml
  server/src/app_state.rs
  server/src/service/get/mod.rs
  webpack.config.js
Labels: 2-documentation, 2-enhancement, automerge

#136 :art: added http header
  server/src/app_state.rs
  server/src/lib.rs
  server/src/middlewares/https.rs
  server/src/middlewares/mod.rs
  server/src/service/get/mod.rs
  server/src/service/get/ws.rs
  server/src/service/mod.rs
Labels: 1-server-http, 2-enhancement, 3-rust, automerge

#137 :construction_worker: fixed coverage
  .github/workflows/coverage.yml
Labels: automerge

#138 :art: improved websocket
  client/src/ws/list.rs
  client/src/ws/room_user.rs
  public/js/index.js
  public/js/modules/websocket.js
  public/js/modules/ws.js
Labels: 1-client-wasm, 1-client-web, 2-enhancement, 3-javascript, 3-rust, automerge

#139 :card_file_box: changed sql
  server/src/actor/list.rs
  server/src/actor/main.rs
  server/src/actor/observe.rs
  server/src/actor/room.rs
  server/src/actor/room_user.rs
  server/src/actor/user.rs
  server/src/app_state.rs
  server/src/db/mod.rs
  server/src/db/sql/create_chat.sql
  server/src/db/sql/create_room.sql
  server/src/db/sql/create_user.sql
  server/src/lib.rs
  server/src/service/get/ws.rs
  sql/create_room.sql
  sql/create_user.sql
  types/src/lib.rs
Labels: 1-server-http, 2-enhancement, 3-rust, automerge

#140 :memo: fixed wrong documents
  README.md
  webpack.config.js
Labels: 2-documentation, automerge

#141 :bug: fixed js
  public/js/index.js
  public/js/modules/websocket.js
Labels: 2-bug, automerge

#143 :rotating_light: fixed js
  public/js/index.js
  public/js/modules/websocket.js
  public/res/scss/style.scss
  webpack.config.js
Labels: automerge

#144 :card_file_box: added login/register feature
  server.sample.toml
  server/src/actor/mail.rs
  server/src/app_state.rs
  server/src/config.rs
  server/src/db/sql/create_room.sql
  server/src/db/sql/create_user.sql
  server/src/db/user.rs
  server/src/lib.rs
  server/src/service/get/mod.rs
  server/src/service/post.rs
Labels: automerge

#146 :card_file_box: added login/register module for js
  package.json
  public/js/modules/user.js
  server/src/db/user.rs
  server/src/service/delete.rs
  server/src/service/get/mod.rs
  server/src/service/mod.rs
  server/src/service/post.rs
Labels: automerge

#147 :art: improved login/register
  public/index.hbs
  public/js/index.js
  public/js/modules/user.js
  server/src/db/user.rs
  types/src/lib.rs
Labels: automerge

#148 :truck: removed bulma
  .github/workflows/build.yml
  .github/workflows/clippy.yml
  .github/workflows/public.yml
  .github/workflows/test.yml
  .gitignore
  Dockerfile
  mighty/src/rule/mod.rs
  mighty/src/state.rs
  minify_files.py
  package.json
  public/index.hbs
  public/js/index.js
  public/src/js/index.js
  public/src/js/modules/user.js
  public/src/js/modules/websocket.js
  public/src/scss/index.scss
  public/src/scss/modules/common.scss
  requirements.txt
  webpack.config.js
Labels: automerge

#149 :memo: fixed documentation
  README.md
Labels: automerge

#150 changed sql query
  server/src/actor/hub.rs
  server/src/actor/room.rs
  server/src/actor/user.rs
  server/src/db/game.rs
  server/src/db/sql/create_room.sql
Labels: automerge

#151 :bento: added wasm fallback
  .gitignore
  public/src/js/index.js
  public/src/js/modules/wasm.js
  server/src/app_state.rs
Labels: automerge

#153 :card_file_box: added user id & email validation
  public/src/js/404.js
  public/src/js/game.js
  public/src/js/index.js
  public/src/js/main.js
  public/src/js/modules/user.js
  public/src/js/modules/wasm.js
  public/src/scss/404.scss
  public/src/scss/game.scss
  public/src/scss/main.scss
  server/src/actor/hub.rs
  server/src/actor/room.rs
  server/src/actor/user.rs
  server/src/db/game.rs
  server/src/db/user.rs
  server/src/service/delete.rs
  server/src/service/get/mod.rs
  server/src/service/post.rs
Labels: automerge

#155 :wrench: fixed dockerfile
  Dockerfile
Labels: automerge

#152 update state.rs test
  mighty/src/state.rs
Labels: automerge

#156 made chat
  client/src/ws/observe.rs
  client/src/ws/room_user.rs
  server/src/actor/observe.rs
  server/src/actor/room.rs
  server/src/actor/user.rs
  server/src/db/game.rs
  server/src/service/get/ws.rs
  types/src/lib.rs
Labels: automerge

#157 :lipstick: added front page
  public/index.hbs
  public/src/js/index.js
  public/src/scss/index.scss
  public/src/scss/modules/box.scss
  public/src/scss/modules/button.scss
  public/src/scss/modules/color.scss
  public/src/scss/modules/common.scss
  public/src/scss/modules/font.scss
Labels: automerge

#158 :lipstick: made login page
  package.json
  public/index.hbs
  public/login.hbs
  public/src/js/login.js
  public/src/js/modules/hash.js
  public/src/js/modules/user.js
  public/src/scss/login.scss
  public/src/scss/modules/button.scss
  server/src/db/sql/drop.sql
  server/src/db/user.rs
  webpack.config.js
Labels: automerge

#159 :white_check_mark: some tests update
  mighty/src/state.rs
Labels: automerge

#161 :rotating_light: fixed compile error for temporarily
  server/Cargo.toml
Labels: automerge

#160 fix bug
  mighty/src/rule/joker_call.rs
  mighty/src/rule/mod.rs
  mighty/src/state.rs
Labels: automerge

#164 :zap: changed host
  public/src/js/register.js
  server/src/config.rs
Labels: automerge

#166 :art: changed to iter
  mighty/src/rule/mod.rs
  mighty/src/state.rs
Labels: automerge

#169 :bug: fixed error when smtp on docker image
  Dockerfile
  README.md
Labels: automerge

#170 :bug: fixed small bugs
  public/src/js/modules/user.js
  public/src/js/pre-register.js
  public/src/js/register.js
  server/src/db/user.rs
  server/src/lib.rs
Labels: automerge

#171 :arrow_up: removed temporary code
  server/Cargo.toml
Labels: automerge

#172 :children_crossing: blocking button when pressed
  public/src/js/login.js
  public/src/js/pre-register.js
  public/src/js/register.js
Labels: automerge

#173 :art: improved structure
  mighty/src/state.rs
Labels: automerge

#176 :art: improved deck
  mighty/src/rule/deck.rs
  mighty/src/rule/mod.rs
  mighty/src/state.rs
Labels: automerge

#175 change card number range
  mighty/src/card.rs
  mighty/src/rule/deck.rs
  mighty/src/rule/joker_call.rs
  mighty/src/rule/mod.rs
  mighty/src/state.rs
Labels: automerge

#178 :art: improved structure
  mighty/src/card.rs
  mighty/src/state.rs
Labels: automerge

#179 :rotating_light: fixed js warnings
  public/src/js/modules/wasm.js
  public/src/js/modules/websocket.js
Labels: automerge

#180 :lipstick: added pre-register-complete page
  public/pre-register-complete.hbs
  public/src/js/modules/user.js
  public/src/js/pre-register-complete.js
  public/src/scss/pre-register-complete.scss
  server/src/service/get/mod.rs
  server/src/service/mod.rs
Labels: automerge

#181 :bug: fixed bug
  mighty/src/state.rs
Labels: automerge

#182 :lipstick: added register-complete
  client/src/ws/list.rs
  public/register-complete.hbs
  public/src/js/register-complete.js
  public/src/scss/register-complete.scss
  server/src/service/get/mod.rs
  server/src/service/mod.rs
Labels: automerge

#183 made simple calculate winner test
  mighty/src/state.rs
  server/src/db/game.rs
Labels: automerge
